# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fpopPSD_cpp <- function(y, beta, alpha, sampling_method, sampling_method_parameter, wt) {
    .Call(`_FpopPSD_fpopPSD_cpp`, y, beta, alpha, sampling_method, sampling_method_parameter, wt)
}

opPSD_cpp <- function(y, beta, alpha, wt) {
    .Call(`_FpopPSD_opPSD_cpp`, y, beta, alpha, wt)
}

