# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fpopPSD <- function(y, beta, alpha, sampling_method, sampling_method_parameter, wt) {
    .Call(`_FpopPSD_fpopPSD`, y, beta, alpha, sampling_method, sampling_method_parameter, wt)
}

opPSD <- function(y, beta, alpha, wt) {
    .Call(`_FpopPSD_opPSD`, y, beta, alpha, wt)
}

